// <auto-generated />
namespace MyStore.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Synch_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Synch_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202201150844317_Synch_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
